// <auto-generated />
using System;
using AcessibilidadeWebAPI.BancoDados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcessibilidadeWebAPI.Migrations
{
    [DbContext(typeof(AcessibilidadeDbContext))]
    [Migration("20250626195507_AddTableAssistencia")]
    partial class AddTableAssistencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.Assistencia", b =>
                {
                    b.Property<int>("IdAssistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAssistencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAssistencia"));

                    b.Property<DateTimeOffset>("DataAceite")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dataAceite");

                    b.Property<DateTimeOffset>("DataConclusao")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dataConclusao");

                    b.Property<int>("IdSolicitacaoAjuda")
                        .HasColumnType("int")
                        .HasColumnName("idSolicitacaoAjuda");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.HasKey("IdAssistencia");

                    b.HasIndex("IdSolicitacaoAjuda");

                    b.HasIndex("IdUsuario");

                    b.ToTable("assistencia", (string)null);
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.AvaliacaoLocal", b =>
                {
                    b.Property<int>("IdAvaliacaoLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacaoLocal"));

                    b.Property<bool>("Acessivel")
                        .HasColumnType("bit")
                        .HasColumnName("acessivel");

                    b.Property<int>("IdLocal")
                        .HasColumnType("int")
                        .HasColumnName("idLocal");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacao");

                    b.Property<int>("Timestamp")
                        .HasColumnType("int")
                        .HasColumnName("timestamp");

                    b.HasKey("IdAvaliacaoLocal");

                    b.HasIndex("IdLocal");

                    b.ToTable("avaliacaoLocal", (string)null);
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.Deficiente", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<int>("TipoDeficiencia")
                        .HasColumnType("int")
                        .HasColumnName("tipoDeficiencia");

                    b.HasKey("IdUsuario");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_deficiente_idUsuario");

                    b.ToTable("deficiente", (string)null);
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.Local", b =>
                {
                    b.Property<int>("IdLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLocal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocal"));

                    b.Property<int>("AvaliacaoAcessibilidade")
                        .HasColumnType("int")
                        .HasColumnName("avaliacaoAcessibilidade");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<int>("Latitude")
                        .HasColumnType("int")
                        .HasColumnName("latitude");

                    b.Property<int>("Longitude")
                        .HasColumnType("int")
                        .HasColumnName("longitude");

                    b.HasKey("IdLocal");

                    b.ToTable("local", (string)null);
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.SolicitacaoAjuda", b =>
                {
                    b.Property<int>("IdSolicitacaoAjuda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSolicitacaoAjuda");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitacaoAjuda"));

                    b.Property<DateTimeOffset>("DataResposta")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dataResposta");

                    b.Property<DateTimeOffset>("DataSolicitacao")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dataSolicitacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("IdSolicitacaoAjuda");

                    b.HasIndex("IdUsuario");

                    b.ToTable("solicitacaoAjuda", (string)null);
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.Voluntario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<int>("Avaliacao")
                        .HasColumnType("int")
                        .HasColumnName("avaliacao");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit")
                        .HasColumnName("disponivel");

                    b.HasKey("IdUsuario");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_voluntario_idUsuario");

                    b.ToTable("voluntario", (string)null);
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.Assistencia", b =>
                {
                    b.HasOne("AcessibilidadeWebAPI.Entidades.SolicitacaoAjuda", "IdSolicitacaoAjudaNavigation")
                        .WithMany("Assistencias")
                        .HasForeignKey("IdSolicitacaoAjuda")
                        .IsRequired()
                        .HasConstraintName("FK_assistencia_idSolicitacaoAjuda_solicitacaoAjuda_idSolicitacaoAjuda");

                    b.HasOne("AcessibilidadeWebAPI.Entidades.Deficiente", "IdUsuarioNavigation")
                        .WithMany("Assistencias")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_assistencia_idUsuario_deficiente_idUsuario");

                    b.Navigation("IdSolicitacaoAjudaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.AvaliacaoLocal", b =>
                {
                    b.HasOne("AcessibilidadeWebAPI.Entidades.Local", "IdLocalNavigation")
                        .WithMany("AvaliacaoLocals")
                        .HasForeignKey("IdLocal")
                        .IsRequired()
                        .HasConstraintName("FK_avaliacaoLocal_idLocal_local_idLocal");

                    b.Navigation("IdLocalNavigation");
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.Deficiente", b =>
                {
                    b.HasOne("AcessibilidadeWebAPI.Entidades.Usuario", "IdUsuarioNavigation")
                        .WithMany("Deficientes")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_deficiente_idUsuario_usuario_idUsuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.SolicitacaoAjuda", b =>
                {
                    b.HasOne("AcessibilidadeWebAPI.Entidades.Deficiente", "IdUsuarioNavigation")
                        .WithMany("SolicitacaoAjudas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_solicitacaoAjudae_idUsuario_deficiente_idUsuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.Voluntario", b =>
                {
                    b.HasOne("AcessibilidadeWebAPI.Entidades.Usuario", "IdUsuarioNavigation")
                        .WithMany("Voluntarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_voluntario_idUsuario_usuario_idUsuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.Deficiente", b =>
                {
                    b.Navigation("Assistencias");

                    b.Navigation("SolicitacaoAjudas");
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.Local", b =>
                {
                    b.Navigation("AvaliacaoLocals");
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.SolicitacaoAjuda", b =>
                {
                    b.Navigation("Assistencias");
                });

            modelBuilder.Entity("AcessibilidadeWebAPI.Entidades.Usuario", b =>
                {
                    b.Navigation("Deficientes");

                    b.Navigation("Voluntarios");
                });
#pragma warning restore 612, 618
        }
    }
}
